# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bb797e04d2a47d9951a9e0721c37f2d393f9e1af557123208cc89d896d1422f384738ce4da4c5ea26f60886bd44392551df324d6661848219b03e81c026f9d8

test:
  secret_key_base: 8b8b415d49116eb56c1ef4172c55a2cad4b7a865edceebd1e23dc9adfb382374bbf04712ace870854f8b191d5a3940b471979516ebc3dd3d178b09388d8f6b77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
